---
- name: install nginx
  apt: 
    name: nginx 
    state: present
    update_cache: yes
  
- name: deactivate default nginx site
  file: 
    path: "{{ nginx_active_sites }}/default"
    state: absent
  when: nginx_disable_default

- name: copy nginx module
  copy:
    src: mod
    dest: "{{ nginx_home }}"

- name: add default config
  template: 
    src: nginx.conf
    dest: "{{ nginx_config }}"
  notify:
    - reload nginx

- import_tasks: site.yml
  when: nginx_create_site
  tags:
    - sites