---
- hosts: lafiya
  remote_user: arewa
  become: yes
  vars:
    - certbot_domains:
      - tsaron.com
      - www.tsaron.com
      - lafiya.tsaron.com
    - certbot_email: postmaster@tsaron.com
    - nginx_create_site: true
    - site_domain: 'lafiya.tsaron.com'
    - ssl_home: /etc/letsencrypt/live/tsaron.com/
    - site_certificate: "{{ ssl_home }}/fullchain.pem"
    - site_ca_certificate: "{{ ssl_home }}/chain.pem"
    - site_certificate_key: "{{ ssl_home }}/privkey.pem"
    - site_dhparam: "{{ ssl_home }}/dhparam.pem"
    - site_web_root: /home/arewa
    - site_is_app: true
    - site_servers:
      - localhost:3000
    - site_app_type: ember
    - site_couchdb_is_hosted: true
    - node_version: node_6.x
    - lafiya_client_root: /srv/arewa/lafiya/app
    - lafiya_client_repo: https://github.com/tsaron/dariya.git
    - lafiya_server_root: /srv/arewa/lafiya/service
    - lafiya_server_repo: https://github.com/tsaron/lafiya-backend.git
  roles:
    - {role: init, tags: init}
    - {role: nginx, tags: ['server', 'ssl']}
    - {role: certbot, tags: ssl}
    - {role: nodejs, tags: nodejs}
    - {role: couchdb, tags: ['db', 'server']}
    - {role: app, tags: app}
  tasks:
    - name: upgrade everything
      apt: upgrade=dist update_cache=yes