---
- name: install couchdb
  block:
    - apt_key: url={{ couch_gpg_key }}
    - apt_repository: repo='deb {{ couchdb_source }} {{ ansible_distribution_release }} main' 
    - apt: name=couchdb update_cache=yes