- name: install nodejs
  block:
    - apt_key: url={{ node_gpg_key }}
    - apt_repository: repo='deb {{ node_source }}/{{ node_version }} {{ ansible_distribution_release }} main' 
    - apt: name={{ item }} update_cache=yes
      with_items:
        - build-essential
        - python
        - python-pip
        - nodejs