---
- name: reload nginx
  service:
    name: nginx
    state: reloaded

- name: start nginx
  service:
    name: nginx
    state: started

- name: stop nginx
  service:
    name: nginx
    state: stopped