---
- name: confirm all variables have been set
  fail: 
    msg: "{{ item }} is not defined"
  when: item is not defined
  with_items:
    - certbot_domains
    - certbot_email

- name: install certbot
  block:
    - apt_repository: repo=ppa:certbot/certbot
    - apt: name=certbot state=present update_cache=yes
      notify:
        - stop nginx

- name: generate dhparams file
  command: openssl dhparam -out /etc/letsencrypt/live/{{ certbot_domains[0] }}/dhparam.pem 2048
  args:
    creates: /etc/letsencrypt/live/{{ certbot_domains[0] }}/dhparam.pem

- name: create certificates
  command: certbot certonly --standalone -n --agree-tos -m {{ certbot_email }} -d {{ certbot_domains|join(', ') }}
  args:
    creates: "/etc/letsencrypt/live/{{ certbot_domains[0] }}/fullchain.pem"
  notify:
    - start nginx